# Default values for e2adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
dummyRanConnection: true
e2SctpPort: 36422
e2NodeType: 1
enbType: 3

imagePullPolicy: IfNotPresent
image:
  name: e2adapter 
  tag: 1.0.0
  registry: "snapshot.docker.ranco-dev-tools.eastus.cloudapp.azure.com:10001"

nameOverride: ""
fullnameOverride: ""


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
