name: Snyk SCA

on:
    push:
        branches: [ "main" ]
    schedule:
        - cron: 0 12 * * 1
    # At 12:00 on Monday.
    
jobs:
  update-repo:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - name: Make the script executable
      run: chmod +x update_repo.sh
      
    - name: Run update_repo.sh
      run: ./update_repo.sh osc  # Change 'osc' to 'onos' or 'aic' as needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  Snyk-Scan:
    permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    needs: update-repo
    # Importing a reusable workflow from another repository and branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
        # This is where you will need to introduce the Snyk API token created with your Snyk account
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Authenticating snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        
        # Use || true to not fail the pipeline
      - name: Snyk Code test
        run: snyk test --all-projects --json > snyk_results.json || true

      - name: Snyk Code test
        run: snyk test --all-projects --sarif > snyk-code.sarif || true

      - name: Save the json file vulnerability report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: snyk_results.json
          path: ./snyk_results.json


      - name: Save the json file vulnerability report
        uses: actions/upload-artifact@master
        if: always()
        with:
            name: snyk-code.sarif
            path: snyk-code.sarif
        
      - name: filter-sarif
        uses: advanced-security/filter-sarif@v1
        with:
            patterns: |
              +**/*.j
              -**/*Test*.java
            input: snyk-code.sarif 
            output: snyk-code.sarif 
        
        # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
          category: snyk

