name: Snyk SCA

on:
    push:
        branches: [ "main" ]
    schedule:
        - cron: 0 12 * * 1
    # At 12:00 on Monday.
    
jobs:
  Snyk-Scan:
    permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    # Importing a reusable workflow from another repository and branch
    uses: t-kolev/Continuous-SCA-Scanning/.github/workflows/snyk.yaml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}